//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBitacora
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMotivoEstadoWO
    {
        public int id { get; set; }
        public Nullable<int> idCatEstadoWO { get; set; }
        public Nullable<int> ClaveRemedy { get; set; }
        public string Descripcion { get; set; }
    }
}
