//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBitacora
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InterEntities : DbContext
    {
        public InterEntities()
            : base("name=InterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatEstadoIncidente> CatEstadoIncidente { get; set; }
        public virtual DbSet<CatEstadoWO> CatEstadoWO { get; set; }
        public virtual DbSet<CatFuenteReportada> CatFuenteReportada { get; set; }
        public virtual DbSet<CatImpactoIncidente> CatImpactoIncidente { get; set; }
        public virtual DbSet<CatMotivoEstadoIncidente> CatMotivoEstadoIncidente { get; set; }
        public virtual DbSet<CatMotivoEstadoWO> CatMotivoEstadoWO { get; set; }
        public virtual DbSet<CatPrioridadWO> CatPrioridadWO { get; set; }
        public virtual DbSet<CatTipoIncidencia> CatTipoIncidencia { get; set; }
        public virtual DbSet<CatTipoOperacionIncidente> CatTipoOperacionIncidente { get; set; }
        public virtual DbSet<CatTipoOperacionWO> CatTipoOperacionWO { get; set; }
        public virtual DbSet<CatUrgenciaIncidente> CatUrgenciaIncidente { get; set; }
        public virtual DbSet<Incidente> Incidente { get; set; }
        public virtual DbSet<IncidenteNotas> IncidenteNotas { get; set; }
        public virtual DbSet<IncidentesDocumentos> IncidentesDocumentos { get; set; }
        public virtual DbSet<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual DbSet<OrdenTrabajoDocumentos> OrdenTrabajoDocumentos { get; set; }
        public virtual DbSet<OrdenTrabajoNotas> OrdenTrabajoNotas { get; set; }
    }
}
