//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBitacora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int id { get; set; }
        public int TicketInvgate { get; set; }
        public string CategoriaPro03 { get; set; }
        public Nullable<bool> Enviado { get; set; }
        public Nullable<System.DateTime> Inclusion { get; set; }
        public Nullable<int> Tipo { get; set; }
    }
}
