//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBitacora
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacionAgente
    {
        public int id { get; set; }
        public string Area { get; set; }
        public string Aplicativo { get; set; }
        public string GrupoSoporte { get; set; }
        public int IdUsuarioInvgate { get; set; }
        public string Agente { get; set; }
        public string Correo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> Inclusion { get; set; }
    }
}
