//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBitacora
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenTrabajo()
        {
            this.OrdenTrabajoDocumentos = new HashSet<OrdenTrabajoDocumentos>();
            this.OrdenTrabajoNotas = new HashSet<OrdenTrabajoNotas>();
        }
    
        public int id { get; set; }
        public string TicketRemedy { get; set; }
        public Nullable<int> TicketInvgate { get; set; }
        public string Descripcion { get; set; }
        public string Resumen { get; set; }
        public string Prioridad { get; set; }
        public string FuenteReportada { get; set; }
        public string NombreProducto { get; set; }
        public string GrupoSoporte { get; set; }
        public string CategoriaOpe01 { get; set; }
        public string CategoriaOpe02 { get; set; }
        public string CategoriaOpe03 { get; set; }
        public string CategoriaPro01 { get; set; }
        public string CategoriaPro02 { get; set; }
        public string CategoriaPro03 { get; set; }
        public string Estado { get; set; }
        public string Motivo { get; set; }
        public string FechaCreacion { get; set; }
        public string Cliente { get; set; }
        public Nullable<bool> VIP { get; set; }
        public string Sensibilidad { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Inclusion { get; set; }
        public string Req { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoDocumentos> OrdenTrabajoDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoNotas> OrdenTrabajoNotas { get; set; }
    }
}
