//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.8.3928.0.
// 
namespace TaskIncidencias.WS_Helix {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MesaHelixSoap", Namespace="urn:imss:helix-invgate")]
    public partial class MesaHelix : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IncidenteActualizaOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncidenteAdicionaNotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrdenTrabajoActualizaOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrdenTrabajoAdicionaNotasOperationCompleted;
        
        /// <remarks/>
        public MesaHelix() {
            this.Url = "http://localhost:51849/Helix/ConnHelix.asmx";
        }
        
        /// <remarks/>
        public event IncidenteActualizaCompletedEventHandler IncidenteActualizaCompleted;
        
        /// <remarks/>
        public event IncidenteAdicionaNotasCompletedEventHandler IncidenteAdicionaNotasCompleted;
        
        /// <remarks/>
        public event OrdenTrabajoActualizaCompletedEventHandler OrdenTrabajoActualizaCompleted;
        
        /// <remarks/>
        public event OrdenTrabajoAdicionaNotasCompletedEventHandler OrdenTrabajoAdicionaNotasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:imss:helix-invgate/IncidenteActualiza", RequestNamespace="urn:imss:helix-invgate", ResponseNamespace="urn:imss:helix-invgate", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result IncidenteActualiza(ActualizacionIncidencia incidente) {
            object[] results = this.Invoke("IncidenteActualiza", new object[] {
                        incidente});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIncidenteActualiza(ActualizacionIncidencia incidente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IncidenteActualiza", new object[] {
                        incidente}, callback, asyncState);
        }
        
        /// <remarks/>
        public Result EndIncidenteActualiza(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void IncidenteActualizaAsync(ActualizacionIncidencia incidente) {
            this.IncidenteActualizaAsync(incidente, null);
        }
        
        /// <remarks/>
        public void IncidenteActualizaAsync(ActualizacionIncidencia incidente, object userState) {
            if ((this.IncidenteActualizaOperationCompleted == null)) {
                this.IncidenteActualizaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncidenteActualizaOperationCompleted);
            }
            this.InvokeAsync("IncidenteActualiza", new object[] {
                        incidente}, this.IncidenteActualizaOperationCompleted, userState);
        }
        
        private void OnIncidenteActualizaOperationCompleted(object arg) {
            if ((this.IncidenteActualizaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncidenteActualizaCompleted(this, new IncidenteActualizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:imss:helix-invgate/IncidenteAdicionaNotas", RequestNamespace="urn:imss:helix-invgate", ResponseNamespace="urn:imss:helix-invgate", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result IncidenteAdicionaNotas(BitacoraTrabajoIncidencia nota) {
            object[] results = this.Invoke("IncidenteAdicionaNotas", new object[] {
                        nota});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIncidenteAdicionaNotas(BitacoraTrabajoIncidencia nota, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IncidenteAdicionaNotas", new object[] {
                        nota}, callback, asyncState);
        }
        
        /// <remarks/>
        public Result EndIncidenteAdicionaNotas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void IncidenteAdicionaNotasAsync(BitacoraTrabajoIncidencia nota) {
            this.IncidenteAdicionaNotasAsync(nota, null);
        }
        
        /// <remarks/>
        public void IncidenteAdicionaNotasAsync(BitacoraTrabajoIncidencia nota, object userState) {
            if ((this.IncidenteAdicionaNotasOperationCompleted == null)) {
                this.IncidenteAdicionaNotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncidenteAdicionaNotasOperationCompleted);
            }
            this.InvokeAsync("IncidenteAdicionaNotas", new object[] {
                        nota}, this.IncidenteAdicionaNotasOperationCompleted, userState);
        }
        
        private void OnIncidenteAdicionaNotasOperationCompleted(object arg) {
            if ((this.IncidenteAdicionaNotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncidenteAdicionaNotasCompleted(this, new IncidenteAdicionaNotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:imss:helix-invgate/OrdenTrabajoActualiza", RequestNamespace="urn:imss:helix-invgate", ResponseNamespace="urn:imss:helix-invgate", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result OrdenTrabajoActualiza(ActualizacionOrdenTrabajo ordenTrabajo) {
            object[] results = this.Invoke("OrdenTrabajoActualiza", new object[] {
                        ordenTrabajo});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOrdenTrabajoActualiza(ActualizacionOrdenTrabajo ordenTrabajo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OrdenTrabajoActualiza", new object[] {
                        ordenTrabajo}, callback, asyncState);
        }
        
        /// <remarks/>
        public Result EndOrdenTrabajoActualiza(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void OrdenTrabajoActualizaAsync(ActualizacionOrdenTrabajo ordenTrabajo) {
            this.OrdenTrabajoActualizaAsync(ordenTrabajo, null);
        }
        
        /// <remarks/>
        public void OrdenTrabajoActualizaAsync(ActualizacionOrdenTrabajo ordenTrabajo, object userState) {
            if ((this.OrdenTrabajoActualizaOperationCompleted == null)) {
                this.OrdenTrabajoActualizaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrdenTrabajoActualizaOperationCompleted);
            }
            this.InvokeAsync("OrdenTrabajoActualiza", new object[] {
                        ordenTrabajo}, this.OrdenTrabajoActualizaOperationCompleted, userState);
        }
        
        private void OnOrdenTrabajoActualizaOperationCompleted(object arg) {
            if ((this.OrdenTrabajoActualizaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrdenTrabajoActualizaCompleted(this, new OrdenTrabajoActualizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:imss:helix-invgate/OrdenTrabajoAdicionaNotas", RequestNamespace="urn:imss:helix-invgate", ResponseNamespace="urn:imss:helix-invgate", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result OrdenTrabajoAdicionaNotas(BitacoraTrabajoOrdenTrabajo nota) {
            object[] results = this.Invoke("OrdenTrabajoAdicionaNotas", new object[] {
                        nota});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOrdenTrabajoAdicionaNotas(BitacoraTrabajoOrdenTrabajo nota, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OrdenTrabajoAdicionaNotas", new object[] {
                        nota}, callback, asyncState);
        }
        
        /// <remarks/>
        public Result EndOrdenTrabajoAdicionaNotas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void OrdenTrabajoAdicionaNotasAsync(BitacoraTrabajoOrdenTrabajo nota) {
            this.OrdenTrabajoAdicionaNotasAsync(nota, null);
        }
        
        /// <remarks/>
        public void OrdenTrabajoAdicionaNotasAsync(BitacoraTrabajoOrdenTrabajo nota, object userState) {
            if ((this.OrdenTrabajoAdicionaNotasOperationCompleted == null)) {
                this.OrdenTrabajoAdicionaNotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrdenTrabajoAdicionaNotasOperationCompleted);
            }
            this.InvokeAsync("OrdenTrabajoAdicionaNotas", new object[] {
                        nota}, this.OrdenTrabajoAdicionaNotasOperationCompleted, userState);
        }
        
        private void OnOrdenTrabajoAdicionaNotasOperationCompleted(object arg) {
            if ((this.OrdenTrabajoAdicionaNotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrdenTrabajoAdicionaNotasCompleted(this, new OrdenTrabajoAdicionaNotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:imss:helix-invgate")]
    public partial class ActualizacionIncidencia {
        
        private string tipoOperacionField;
        
        private string tipoTicketField;
        
        private string idIncidenciaField;
        
        private string ticketProveedorField;
        
        private string estadoNuevoField;
        
        private string motivoEstadoNuevoField;
        
        private string categoriaResolucion1Field;
        
        private string categoriaResolucion2Field;
        
        private string categoriaResolucion3Field;
        
        private string resolucionField;
        
        /// <remarks/>
        public string TipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        public string TipoTicket {
            get {
                return this.tipoTicketField;
            }
            set {
                this.tipoTicketField = value;
            }
        }
        
        /// <remarks/>
        public string IdIncidencia {
            get {
                return this.idIncidenciaField;
            }
            set {
                this.idIncidenciaField = value;
            }
        }
        
        /// <remarks/>
        public string TicketProveedor {
            get {
                return this.ticketProveedorField;
            }
            set {
                this.ticketProveedorField = value;
            }
        }
        
        /// <remarks/>
        public string EstadoNuevo {
            get {
                return this.estadoNuevoField;
            }
            set {
                this.estadoNuevoField = value;
            }
        }
        
        /// <remarks/>
        public string MotivoEstadoNuevo {
            get {
                return this.motivoEstadoNuevoField;
            }
            set {
                this.motivoEstadoNuevoField = value;
            }
        }
        
        /// <remarks/>
        public string CategoriaResolucion1 {
            get {
                return this.categoriaResolucion1Field;
            }
            set {
                this.categoriaResolucion1Field = value;
            }
        }
        
        /// <remarks/>
        public string CategoriaResolucion2 {
            get {
                return this.categoriaResolucion2Field;
            }
            set {
                this.categoriaResolucion2Field = value;
            }
        }
        
        /// <remarks/>
        public string CategoriaResolucion3 {
            get {
                return this.categoriaResolucion3Field;
            }
            set {
                this.categoriaResolucion3Field = value;
            }
        }
        
        /// <remarks/>
        public string Resolucion {
            get {
                return this.resolucionField;
            }
            set {
                this.resolucionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:imss:helix-invgate")]
    public partial class BitacoraTrabajoOrdenTrabajo {
        
        private string tipoOperacionField;
        
        private string tipoTicketField;
        
        private string idOrdenTrabajoField;
        
        private string ticketProveedorField;
        
        private string notasField;
        
        private string adjunto1NombreField;
        
        private string adjunto1DatosField;
        
        private System.Nullable<int> adjunto1TamanoField;
        
        private string adjunto2NombreField;
        
        private string adjunto2DatosField;
        
        private System.Nullable<int> adjunto2TamanoField;
        
        private string adjunto3NombreField;
        
        private string adjunto3DatosField;
        
        private System.Nullable<int> adjunto3TamanoField;
        
        /// <remarks/>
        public string TipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        public string TipoTicket {
            get {
                return this.tipoTicketField;
            }
            set {
                this.tipoTicketField = value;
            }
        }
        
        /// <remarks/>
        public string IdOrdenTrabajo {
            get {
                return this.idOrdenTrabajoField;
            }
            set {
                this.idOrdenTrabajoField = value;
            }
        }
        
        /// <remarks/>
        public string TicketProveedor {
            get {
                return this.ticketProveedorField;
            }
            set {
                this.ticketProveedorField = value;
            }
        }
        
        /// <remarks/>
        public string Notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto1Nombre {
            get {
                return this.adjunto1NombreField;
            }
            set {
                this.adjunto1NombreField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto1Datos {
            get {
                return this.adjunto1DatosField;
            }
            set {
                this.adjunto1DatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Adjunto1Tamano {
            get {
                return this.adjunto1TamanoField;
            }
            set {
                this.adjunto1TamanoField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto2Nombre {
            get {
                return this.adjunto2NombreField;
            }
            set {
                this.adjunto2NombreField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto2Datos {
            get {
                return this.adjunto2DatosField;
            }
            set {
                this.adjunto2DatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Adjunto2Tamano {
            get {
                return this.adjunto2TamanoField;
            }
            set {
                this.adjunto2TamanoField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto3Nombre {
            get {
                return this.adjunto3NombreField;
            }
            set {
                this.adjunto3NombreField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto3Datos {
            get {
                return this.adjunto3DatosField;
            }
            set {
                this.adjunto3DatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Adjunto3Tamano {
            get {
                return this.adjunto3TamanoField;
            }
            set {
                this.adjunto3TamanoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:imss:helix-invgate")]
    public partial class ActualizacionOrdenTrabajo {
        
        private string tipoOperacionField;
        
        private string tipoTicketField;
        
        private string idOrdenTrabajoField;
        
        private string ticketProveedorField;
        
        private string estadoNuevoField;
        
        private string motivoEstadoNuevoField;
        
        private string notaResolucionField;
        
        /// <remarks/>
        public string TipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        public string TipoTicket {
            get {
                return this.tipoTicketField;
            }
            set {
                this.tipoTicketField = value;
            }
        }
        
        /// <remarks/>
        public string IdOrdenTrabajo {
            get {
                return this.idOrdenTrabajoField;
            }
            set {
                this.idOrdenTrabajoField = value;
            }
        }
        
        /// <remarks/>
        public string TicketProveedor {
            get {
                return this.ticketProveedorField;
            }
            set {
                this.ticketProveedorField = value;
            }
        }
        
        /// <remarks/>
        public string EstadoNuevo {
            get {
                return this.estadoNuevoField;
            }
            set {
                this.estadoNuevoField = value;
            }
        }
        
        /// <remarks/>
        public string MotivoEstadoNuevo {
            get {
                return this.motivoEstadoNuevoField;
            }
            set {
                this.motivoEstadoNuevoField = value;
            }
        }
        
        /// <remarks/>
        public string NotaResolucion {
            get {
                return this.notaResolucionField;
            }
            set {
                this.notaResolucionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:imss:helix-invgate")]
    public partial class BitacoraTrabajoIncidencia {
        
        private string tipoOperacionField;
        
        private string tipoTicketField;
        
        private string idIncidenciaField;
        
        private string ticketProveedorField;
        
        private string notasField;
        
        private string adjunto1NombreField;
        
        private string adjunto1DatosField;
        
        private System.Nullable<int> adjunto1TamanoField;
        
        private string adjunto2NombreField;
        
        private string adjunto2DatosField;
        
        private System.Nullable<int> adjunto2TamanoField;
        
        private string adjunto3NombreField;
        
        private string adjunto3DatosField;
        
        private System.Nullable<int> adjunto3TamanoField;
        
        /// <remarks/>
        public string TipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        public string TipoTicket {
            get {
                return this.tipoTicketField;
            }
            set {
                this.tipoTicketField = value;
            }
        }
        
        /// <remarks/>
        public string IdIncidencia {
            get {
                return this.idIncidenciaField;
            }
            set {
                this.idIncidenciaField = value;
            }
        }
        
        /// <remarks/>
        public string TicketProveedor {
            get {
                return this.ticketProveedorField;
            }
            set {
                this.ticketProveedorField = value;
            }
        }
        
        /// <remarks/>
        public string Notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto1Nombre {
            get {
                return this.adjunto1NombreField;
            }
            set {
                this.adjunto1NombreField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto1Datos {
            get {
                return this.adjunto1DatosField;
            }
            set {
                this.adjunto1DatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Adjunto1Tamano {
            get {
                return this.adjunto1TamanoField;
            }
            set {
                this.adjunto1TamanoField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto2Nombre {
            get {
                return this.adjunto2NombreField;
            }
            set {
                this.adjunto2NombreField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto2Datos {
            get {
                return this.adjunto2DatosField;
            }
            set {
                this.adjunto2DatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Adjunto2Tamano {
            get {
                return this.adjunto2TamanoField;
            }
            set {
                this.adjunto2TamanoField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto3Nombre {
            get {
                return this.adjunto3NombreField;
            }
            set {
                this.adjunto3NombreField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto3Datos {
            get {
                return this.adjunto3DatosField;
            }
            set {
                this.adjunto3DatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Adjunto3Tamano {
            get {
                return this.adjunto3TamanoField;
            }
            set {
                this.adjunto3TamanoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:imss:helix-invgate")]
    public partial class Result {
        
        private bool estatusField;
        
        private string resultadoField;
        
        /// <remarks/>
        public bool Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void IncidenteActualizaCompletedEventHandler(object sender, IncidenteActualizaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncidenteActualizaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncidenteActualizaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void IncidenteAdicionaNotasCompletedEventHandler(object sender, IncidenteAdicionaNotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncidenteAdicionaNotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncidenteAdicionaNotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void OrdenTrabajoActualizaCompletedEventHandler(object sender, OrdenTrabajoActualizaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrdenTrabajoActualizaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrdenTrabajoActualizaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void OrdenTrabajoAdicionaNotasCompletedEventHandler(object sender, OrdenTrabajoAdicionaNotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrdenTrabajoAdicionaNotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrdenTrabajoAdicionaNotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}
