//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TaskIncidencias.WS_Remedy {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MesaIMSSSoap", Namespace="http://tempuri.org/")]
    public partial class MesaIMSS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IncidenteActualizaCategorizacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncidenteActualizaOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncidenteActualizaPrioridadOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncidenteAdicionaNotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrdenTrabajoActualizaCategorizacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrdenTrabajoActualizaOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrdenTrabajoActualizaPrioridadOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrdenTrabajoAdicionaNotasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MesaIMSS() {
            this.Url = global::TaskIncidencias.Properties.Settings.Default.TaskIncidencias_WS_Remedy_MesaIMSS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IncidenteActualizaCategorizacionCompletedEventHandler IncidenteActualizaCategorizacionCompleted;
        
        /// <remarks/>
        public event IncidenteActualizaCompletedEventHandler IncidenteActualizaCompleted;
        
        /// <remarks/>
        public event IncidenteActualizaPrioridadCompletedEventHandler IncidenteActualizaPrioridadCompleted;
        
        /// <remarks/>
        public event IncidenteAdicionaNotasCompletedEventHandler IncidenteAdicionaNotasCompleted;
        
        /// <remarks/>
        public event OrdenTrabajoActualizaCategorizacionCompletedEventHandler OrdenTrabajoActualizaCategorizacionCompleted;
        
        /// <remarks/>
        public event OrdenTrabajoActualizaCompletedEventHandler OrdenTrabajoActualizaCompleted;
        
        /// <remarks/>
        public event OrdenTrabajoActualizaPrioridadCompletedEventHandler OrdenTrabajoActualizaPrioridadCompleted;
        
        /// <remarks/>
        public event OrdenTrabajoAdicionaNotasCompletedEventHandler OrdenTrabajoAdicionaNotasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncidenteActualizaCategorizacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result IncidenteActualizaCategorizacion(Categorizacion categorizacion) {
            object[] results = this.Invoke("IncidenteActualizaCategorizacion", new object[] {
                        categorizacion});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void IncidenteActualizaCategorizacionAsync(Categorizacion categorizacion) {
            this.IncidenteActualizaCategorizacionAsync(categorizacion, null);
        }
        
        /// <remarks/>
        public void IncidenteActualizaCategorizacionAsync(Categorizacion categorizacion, object userState) {
            if ((this.IncidenteActualizaCategorizacionOperationCompleted == null)) {
                this.IncidenteActualizaCategorizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncidenteActualizaCategorizacionOperationCompleted);
            }
            this.InvokeAsync("IncidenteActualizaCategorizacion", new object[] {
                        categorizacion}, this.IncidenteActualizaCategorizacionOperationCompleted, userState);
        }
        
        private void OnIncidenteActualizaCategorizacionOperationCompleted(object arg) {
            if ((this.IncidenteActualizaCategorizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncidenteActualizaCategorizacionCompleted(this, new IncidenteActualizaCategorizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncidenteActualiza", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result IncidenteActualiza(Incidente incidente) {
            object[] results = this.Invoke("IncidenteActualiza", new object[] {
                        incidente});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void IncidenteActualizaAsync(Incidente incidente) {
            this.IncidenteActualizaAsync(incidente, null);
        }
        
        /// <remarks/>
        public void IncidenteActualizaAsync(Incidente incidente, object userState) {
            if ((this.IncidenteActualizaOperationCompleted == null)) {
                this.IncidenteActualizaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncidenteActualizaOperationCompleted);
            }
            this.InvokeAsync("IncidenteActualiza", new object[] {
                        incidente}, this.IncidenteActualizaOperationCompleted, userState);
        }
        
        private void OnIncidenteActualizaOperationCompleted(object arg) {
            if ((this.IncidenteActualizaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncidenteActualizaCompleted(this, new IncidenteActualizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncidenteActualizaPrioridad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result IncidenteActualizaPrioridad(Prioridad prioridad) {
            object[] results = this.Invoke("IncidenteActualizaPrioridad", new object[] {
                        prioridad});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void IncidenteActualizaPrioridadAsync(Prioridad prioridad) {
            this.IncidenteActualizaPrioridadAsync(prioridad, null);
        }
        
        /// <remarks/>
        public void IncidenteActualizaPrioridadAsync(Prioridad prioridad, object userState) {
            if ((this.IncidenteActualizaPrioridadOperationCompleted == null)) {
                this.IncidenteActualizaPrioridadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncidenteActualizaPrioridadOperationCompleted);
            }
            this.InvokeAsync("IncidenteActualizaPrioridad", new object[] {
                        prioridad}, this.IncidenteActualizaPrioridadOperationCompleted, userState);
        }
        
        private void OnIncidenteActualizaPrioridadOperationCompleted(object arg) {
            if ((this.IncidenteActualizaPrioridadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncidenteActualizaPrioridadCompleted(this, new IncidenteActualizaPrioridadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncidenteAdicionaNotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result IncidenteAdicionaNotas(Comentario comentario) {
            object[] results = this.Invoke("IncidenteAdicionaNotas", new object[] {
                        comentario});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void IncidenteAdicionaNotasAsync(Comentario comentario) {
            this.IncidenteAdicionaNotasAsync(comentario, null);
        }
        
        /// <remarks/>
        public void IncidenteAdicionaNotasAsync(Comentario comentario, object userState) {
            if ((this.IncidenteAdicionaNotasOperationCompleted == null)) {
                this.IncidenteAdicionaNotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncidenteAdicionaNotasOperationCompleted);
            }
            this.InvokeAsync("IncidenteAdicionaNotas", new object[] {
                        comentario}, this.IncidenteAdicionaNotasOperationCompleted, userState);
        }
        
        private void OnIncidenteAdicionaNotasOperationCompleted(object arg) {
            if ((this.IncidenteAdicionaNotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncidenteAdicionaNotasCompleted(this, new IncidenteAdicionaNotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrdenTrabajoActualizaCategorizacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result OrdenTrabajoActualizaCategorizacion(Categorizacion categorizacion) {
            object[] results = this.Invoke("OrdenTrabajoActualizaCategorizacion", new object[] {
                        categorizacion});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void OrdenTrabajoActualizaCategorizacionAsync(Categorizacion categorizacion) {
            this.OrdenTrabajoActualizaCategorizacionAsync(categorizacion, null);
        }
        
        /// <remarks/>
        public void OrdenTrabajoActualizaCategorizacionAsync(Categorizacion categorizacion, object userState) {
            if ((this.OrdenTrabajoActualizaCategorizacionOperationCompleted == null)) {
                this.OrdenTrabajoActualizaCategorizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrdenTrabajoActualizaCategorizacionOperationCompleted);
            }
            this.InvokeAsync("OrdenTrabajoActualizaCategorizacion", new object[] {
                        categorizacion}, this.OrdenTrabajoActualizaCategorizacionOperationCompleted, userState);
        }
        
        private void OnOrdenTrabajoActualizaCategorizacionOperationCompleted(object arg) {
            if ((this.OrdenTrabajoActualizaCategorizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrdenTrabajoActualizaCategorizacionCompleted(this, new OrdenTrabajoActualizaCategorizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrdenTrabajoActualiza", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result OrdenTrabajoActualiza(OrdenTrabajo ordenTrabajo) {
            object[] results = this.Invoke("OrdenTrabajoActualiza", new object[] {
                        ordenTrabajo});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void OrdenTrabajoActualizaAsync(OrdenTrabajo ordenTrabajo) {
            this.OrdenTrabajoActualizaAsync(ordenTrabajo, null);
        }
        
        /// <remarks/>
        public void OrdenTrabajoActualizaAsync(OrdenTrabajo ordenTrabajo, object userState) {
            if ((this.OrdenTrabajoActualizaOperationCompleted == null)) {
                this.OrdenTrabajoActualizaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrdenTrabajoActualizaOperationCompleted);
            }
            this.InvokeAsync("OrdenTrabajoActualiza", new object[] {
                        ordenTrabajo}, this.OrdenTrabajoActualizaOperationCompleted, userState);
        }
        
        private void OnOrdenTrabajoActualizaOperationCompleted(object arg) {
            if ((this.OrdenTrabajoActualizaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrdenTrabajoActualizaCompleted(this, new OrdenTrabajoActualizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrdenTrabajoActualizaPrioridad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result OrdenTrabajoActualizaPrioridad(PrioridadOT prioridad) {
            object[] results = this.Invoke("OrdenTrabajoActualizaPrioridad", new object[] {
                        prioridad});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void OrdenTrabajoActualizaPrioridadAsync(PrioridadOT prioridad) {
            this.OrdenTrabajoActualizaPrioridadAsync(prioridad, null);
        }
        
        /// <remarks/>
        public void OrdenTrabajoActualizaPrioridadAsync(PrioridadOT prioridad, object userState) {
            if ((this.OrdenTrabajoActualizaPrioridadOperationCompleted == null)) {
                this.OrdenTrabajoActualizaPrioridadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrdenTrabajoActualizaPrioridadOperationCompleted);
            }
            this.InvokeAsync("OrdenTrabajoActualizaPrioridad", new object[] {
                        prioridad}, this.OrdenTrabajoActualizaPrioridadOperationCompleted, userState);
        }
        
        private void OnOrdenTrabajoActualizaPrioridadOperationCompleted(object arg) {
            if ((this.OrdenTrabajoActualizaPrioridadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrdenTrabajoActualizaPrioridadCompleted(this, new OrdenTrabajoActualizaPrioridadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OrdenTrabajoAdicionaNotas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result OrdenTrabajoAdicionaNotas(Comentario comentario) {
            object[] results = this.Invoke("OrdenTrabajoAdicionaNotas", new object[] {
                        comentario});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void OrdenTrabajoAdicionaNotasAsync(Comentario comentario) {
            this.OrdenTrabajoAdicionaNotasAsync(comentario, null);
        }
        
        /// <remarks/>
        public void OrdenTrabajoAdicionaNotasAsync(Comentario comentario, object userState) {
            if ((this.OrdenTrabajoAdicionaNotasOperationCompleted == null)) {
                this.OrdenTrabajoAdicionaNotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrdenTrabajoAdicionaNotasOperationCompleted);
            }
            this.InvokeAsync("OrdenTrabajoAdicionaNotas", new object[] {
                        comentario}, this.OrdenTrabajoAdicionaNotasOperationCompleted, userState);
        }
        
        private void OnOrdenTrabajoAdicionaNotasOperationCompleted(object arg) {
            if ((this.OrdenTrabajoAdicionaNotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrdenTrabajoAdicionaNotasCompleted(this, new OrdenTrabajoAdicionaNotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Categorizacion {
        
        private string iDTicketRemedyField;
        
        private string iDTicketInvgateField;
        
        private string catOperacion01Field;
        
        private string catOperacion02Field;
        
        private string catOperacion03Field;
        
        private string catProducto01Field;
        
        private string catProducto02Field;
        
        private string catProducto03Field;
        
        /// <remarks/>
        public string IDTicketRemedy {
            get {
                return this.iDTicketRemedyField;
            }
            set {
                this.iDTicketRemedyField = value;
            }
        }
        
        /// <remarks/>
        public string IDTicketInvgate {
            get {
                return this.iDTicketInvgateField;
            }
            set {
                this.iDTicketInvgateField = value;
            }
        }
        
        /// <remarks/>
        public string CatOperacion01 {
            get {
                return this.catOperacion01Field;
            }
            set {
                this.catOperacion01Field = value;
            }
        }
        
        /// <remarks/>
        public string CatOperacion02 {
            get {
                return this.catOperacion02Field;
            }
            set {
                this.catOperacion02Field = value;
            }
        }
        
        /// <remarks/>
        public string CatOperacion03 {
            get {
                return this.catOperacion03Field;
            }
            set {
                this.catOperacion03Field = value;
            }
        }
        
        /// <remarks/>
        public string CatProducto01 {
            get {
                return this.catProducto01Field;
            }
            set {
                this.catProducto01Field = value;
            }
        }
        
        /// <remarks/>
        public string CatProducto02 {
            get {
                return this.catProducto02Field;
            }
            set {
                this.catProducto02Field = value;
            }
        }
        
        /// <remarks/>
        public string CatProducto03 {
            get {
                return this.catProducto03Field;
            }
            set {
                this.catProducto03Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrioridadOT {
        
        private string iDTicketRemedyField;
        
        private string iDTicketInvgateField;
        
        private int prioridadField;
        
        /// <remarks/>
        public string IDTicketRemedy {
            get {
                return this.iDTicketRemedyField;
            }
            set {
                this.iDTicketRemedyField = value;
            }
        }
        
        /// <remarks/>
        public string IDTicketInvgate {
            get {
                return this.iDTicketInvgateField;
            }
            set {
                this.iDTicketInvgateField = value;
            }
        }
        
        /// <remarks/>
        public int Prioridad {
            get {
                return this.prioridadField;
            }
            set {
                this.prioridadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdenTrabajo {
        
        private string iDTicketRemedyField;
        
        private string iDTicketInvgateField;
        
        private int estadoNuevoField;
        
        private int motivoEstadoField;
        
        private string resolucionField;
        
        /// <remarks/>
        public string IDTicketRemedy {
            get {
                return this.iDTicketRemedyField;
            }
            set {
                this.iDTicketRemedyField = value;
            }
        }
        
        /// <remarks/>
        public string IDTicketInvgate {
            get {
                return this.iDTicketInvgateField;
            }
            set {
                this.iDTicketInvgateField = value;
            }
        }
        
        /// <remarks/>
        public int EstadoNuevo {
            get {
                return this.estadoNuevoField;
            }
            set {
                this.estadoNuevoField = value;
            }
        }
        
        /// <remarks/>
        public int MotivoEstado {
            get {
                return this.motivoEstadoField;
            }
            set {
                this.motivoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string Resolucion {
            get {
                return this.resolucionField;
            }
            set {
                this.resolucionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Comentario {
        
        private string iDTicketRemedyField;
        
        private string iDTicketInvgateField;
        
        private string notasField;
        
        private string adjunto01Field;
        
        private string adjuntoName01Field;
        
        private string adjuntoSize01Field;
        
        private string adjunto02Field;
        
        private string adjuntoName02Field;
        
        private string adjuntoSize02Field;
        
        private string adjunto03Field;
        
        private string adjuntoName03Field;
        
        private string adjuntoSize03Field;
        
        /// <remarks/>
        public string IDTicketRemedy {
            get {
                return this.iDTicketRemedyField;
            }
            set {
                this.iDTicketRemedyField = value;
            }
        }
        
        /// <remarks/>
        public string IDTicketInvgate {
            get {
                return this.iDTicketInvgateField;
            }
            set {
                this.iDTicketInvgateField = value;
            }
        }
        
        /// <remarks/>
        public string Notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto01 {
            get {
                return this.adjunto01Field;
            }
            set {
                this.adjunto01Field = value;
            }
        }
        
        /// <remarks/>
        public string AdjuntoName01 {
            get {
                return this.adjuntoName01Field;
            }
            set {
                this.adjuntoName01Field = value;
            }
        }
        
        /// <remarks/>
        public string AdjuntoSize01 {
            get {
                return this.adjuntoSize01Field;
            }
            set {
                this.adjuntoSize01Field = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto02 {
            get {
                return this.adjunto02Field;
            }
            set {
                this.adjunto02Field = value;
            }
        }
        
        /// <remarks/>
        public string AdjuntoName02 {
            get {
                return this.adjuntoName02Field;
            }
            set {
                this.adjuntoName02Field = value;
            }
        }
        
        /// <remarks/>
        public string AdjuntoSize02 {
            get {
                return this.adjuntoSize02Field;
            }
            set {
                this.adjuntoSize02Field = value;
            }
        }
        
        /// <remarks/>
        public string Adjunto03 {
            get {
                return this.adjunto03Field;
            }
            set {
                this.adjunto03Field = value;
            }
        }
        
        /// <remarks/>
        public string AdjuntoName03 {
            get {
                return this.adjuntoName03Field;
            }
            set {
                this.adjuntoName03Field = value;
            }
        }
        
        /// <remarks/>
        public string AdjuntoSize03 {
            get {
                return this.adjuntoSize03Field;
            }
            set {
                this.adjuntoSize03Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Prioridad {
        
        private string iDTicketRemedyField;
        
        private string iDTicketInvgateField;
        
        private int impactoField;
        
        private int urgenciaField;
        
        /// <remarks/>
        public string IDTicketRemedy {
            get {
                return this.iDTicketRemedyField;
            }
            set {
                this.iDTicketRemedyField = value;
            }
        }
        
        /// <remarks/>
        public string IDTicketInvgate {
            get {
                return this.iDTicketInvgateField;
            }
            set {
                this.iDTicketInvgateField = value;
            }
        }
        
        /// <remarks/>
        public int Impacto {
            get {
                return this.impactoField;
            }
            set {
                this.impactoField = value;
            }
        }
        
        /// <remarks/>
        public int Urgencia {
            get {
                return this.urgenciaField;
            }
            set {
                this.urgenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Incidente {
        
        private string iDTicketRemedyField;
        
        private string iDTicketInvgateField;
        
        private string catCierreOperacion01Field;
        
        private string catCierreOperacion02Field;
        
        private string catCierreOperacion03Field;
        
        private string catCierreProducto01Field;
        
        private string catCierreProducto02Field;
        
        private string catCierreProducto03Field;
        
        private int estadoNuevoField;
        
        private int motivoEstadoField;
        
        private string resolucionField;
        
        /// <remarks/>
        public string IDTicketRemedy {
            get {
                return this.iDTicketRemedyField;
            }
            set {
                this.iDTicketRemedyField = value;
            }
        }
        
        /// <remarks/>
        public string IDTicketInvgate {
            get {
                return this.iDTicketInvgateField;
            }
            set {
                this.iDTicketInvgateField = value;
            }
        }
        
        /// <remarks/>
        public string CatCierreOperacion01 {
            get {
                return this.catCierreOperacion01Field;
            }
            set {
                this.catCierreOperacion01Field = value;
            }
        }
        
        /// <remarks/>
        public string CatCierreOperacion02 {
            get {
                return this.catCierreOperacion02Field;
            }
            set {
                this.catCierreOperacion02Field = value;
            }
        }
        
        /// <remarks/>
        public string CatCierreOperacion03 {
            get {
                return this.catCierreOperacion03Field;
            }
            set {
                this.catCierreOperacion03Field = value;
            }
        }
        
        /// <remarks/>
        public string CatCierreProducto01 {
            get {
                return this.catCierreProducto01Field;
            }
            set {
                this.catCierreProducto01Field = value;
            }
        }
        
        /// <remarks/>
        public string CatCierreProducto02 {
            get {
                return this.catCierreProducto02Field;
            }
            set {
                this.catCierreProducto02Field = value;
            }
        }
        
        /// <remarks/>
        public string CatCierreProducto03 {
            get {
                return this.catCierreProducto03Field;
            }
            set {
                this.catCierreProducto03Field = value;
            }
        }
        
        /// <remarks/>
        public int EstadoNuevo {
            get {
                return this.estadoNuevoField;
            }
            set {
                this.estadoNuevoField = value;
            }
        }
        
        /// <remarks/>
        public int MotivoEstado {
            get {
                return this.motivoEstadoField;
            }
            set {
                this.motivoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string Resolucion {
            get {
                return this.resolucionField;
            }
            set {
                this.resolucionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result {
        
        private bool estatusField;
        
        private string resultadoField;
        
        /// <remarks/>
        public bool Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void IncidenteActualizaCategorizacionCompletedEventHandler(object sender, IncidenteActualizaCategorizacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncidenteActualizaCategorizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncidenteActualizaCategorizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void IncidenteActualizaCompletedEventHandler(object sender, IncidenteActualizaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncidenteActualizaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncidenteActualizaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void IncidenteActualizaPrioridadCompletedEventHandler(object sender, IncidenteActualizaPrioridadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncidenteActualizaPrioridadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncidenteActualizaPrioridadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void IncidenteAdicionaNotasCompletedEventHandler(object sender, IncidenteAdicionaNotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncidenteAdicionaNotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncidenteAdicionaNotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void OrdenTrabajoActualizaCategorizacionCompletedEventHandler(object sender, OrdenTrabajoActualizaCategorizacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrdenTrabajoActualizaCategorizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrdenTrabajoActualizaCategorizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void OrdenTrabajoActualizaCompletedEventHandler(object sender, OrdenTrabajoActualizaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrdenTrabajoActualizaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrdenTrabajoActualizaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void OrdenTrabajoActualizaPrioridadCompletedEventHandler(object sender, OrdenTrabajoActualizaPrioridadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrdenTrabajoActualizaPrioridadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrdenTrabajoActualizaPrioridadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void OrdenTrabajoAdicionaNotasCompletedEventHandler(object sender, OrdenTrabajoAdicionaNotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrdenTrabajoAdicionaNotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrdenTrabajoAdicionaNotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591